"""empty message

Revision ID: 88119498e940
Revises: 92ac1cc6fb8f
Create Date: 2020-09-04 21:20:33.715267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88119498e940'
down_revision = '92ac1cc6fb8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
